#!/Users/joebudds/Documents/AI_Relay_Files/jenny_core/venv/bin/python3.13
import sys
from build.__main__ import entrypoint
if __name__ == '__main__':
    if sys.argv[0].endswith('.exe'):
        sys.argv[0] = sys.argv[0][:-4]
    sys.exit(entrypoint())
